Bridge Crew edit interface
zmyaro/star-site pull request #95
Opened 2018-04-19 03:17 UTC by ZMYaro

Closes #64.

2018-05-03 23:33 UTC, noblelady approved these changes
Looks good

2018-05-09 04:07 UTC, dexw25 requested changes
Looks good except for a couple of extra debug statements

2018-05-09 04:07 UTC, derekw023 commented on bridgecrew.py
> +		logging.debug('SNTHOISNTHOISNT')
looks like a leftover debug statement

2018-05-09 04:07 UTC, derekw023 commented on bridgecrew.py
> +		logging.debug('UPDATE RECEIVED!')
Looks like a leftover debug statement

2018-05-10 00:56 UTC, ZMYaro commented
Fixed.  Thanks for catching that, @derekw023!

2018-05-10 01:07 UTC, dexw25 approved these changes
Should be good to go now

2018-05-10 02:24 UTC, merged